spring.application.name=parkingmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/parkingmanager
spring.datasource.username=postgres
spring.datasource.password=parking123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
